import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        <h1 className={styles.title}>

          Vannesa Makatu
        </h1>

        <h2 className={styles.description}>
          
          Associate Developer{' '}
          <code className={styles.code}></code>
        </h2>
        
        
    


        <canvas id="canvas"></canvas>
        <div className="container">
  <div className="card">
    <div className="face face1">
      <div className="content">
        <span className="stars" />
        <h2 className="java">Who is Vannesa?</h2>
        <p className="java">
          Vannesa is a young passionate woman that has the drive to change the
          future of technology. Her dream is to build her own tech empire to
          help other young women in tech to build their careers with no
          discrimation.{" "}
        </p>
      </div>
    </div>
    <div className="face face2">
      <h2>M</h2>
    </div>
  </div>
  <div className="card">
    <div className="face face1">
      <div className="content">
        <span className="stars" />
        <h2 className="python">Achievements</h2>
        <p className="python">
          I may have not reached my life milestones yet, but I have a couple of
          small achievements that I'm proud of such as, earning certifications
          in Safe Agile framework and a certification in Systems Development.
          And the fact that I am a self taught programmer.
        </p>
      </div>
    </div>
    <div className="face face2">
      <h2>V</h2>
    </div>
  </div>
  <div className="card">
    <div className="face face1">
      <div className="content">
        <span className="stars" />
        <h2 className="cSharp">Why do I want to be a developer at SovTech?</h2>
        <p className="cSharp">
          It would actually be such a great honour for myself to be apart of
          SovTech. The company seems like they treat everyone like family. Also
          the fact that you appreciate the art of a professionally gooogling as
          a developer. It will feel like home to be apart of SovTech.
        </p>
      </div>
    </div>
    <div className="face face2">
      <h2>M</h2>
    </div>
  </div>
</div>
<footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      </main>  
     </div>
  )
}  
